CREATE TABLE IF NOT EXISTS resultados (
    id_inscricao BIGINT NOT NULL,
    ano_exame INT, 
    id_municipio_escola INT, 
    id_uf_escola INT,
    dependencia_adm_escola INT, 
    localizacao_escola INT,
    situacao_func_escola INT, 
    id_municipio_prova INT, 
    id_uf_prova INT,  
    presenca_cn INT,
    presenca_ch INT, 
    presenca_lc INT,
    presenca_mt INT, 
    nota_cn NUMERIC(10,2),
    nota_ch	NUMERIC(10,2),
    nota_lc	NUMERIC(10,2),
    nota_mt	NUMERIC(10,2),
    nota_redacao NUMERIC(10,2   ),
    nota_complementar1 NUMERIC(10,2),	
    nota_complementar2 NUMERIC(10,2),
    nota_complementar3 NUMERIC(10,2),
    nota_complementar4 NUMERIC(10,2),
    nota_complementar5 NUMERIC(10,2),
    situacao_redacao INT
);


CREATE TABLE IF NOT EXISTS participantes (
    id_inscricao BIGINT NOT NULL,
    ano_exame INT,
    faixa_etaria INT, 
    sexo CHAR(1),
    estado_civil INT, 
    cor_raca INT,
    nacionalidade INT,
    st_conclusao INT,	
    ano_conclusao INT,
    ensino INT,	
    treineiro INT,
    municipio_prova	INT,
    id_uf_prova INT,	
    questionario_q1 CHAR(1),
    questionario_q2	CHAR(1),
    questionario_q3 CHAR(1),
    questionario_q4	CHAR(1),
    questionario_q5	CHAR(1),
    questionario_q6	CHAR(1),
    questionario_q7	CHAR(1),
    questionario_q8	CHAR(1),
    questionario_q9	CHAR(1),
    questionario_q10 CHAR(1),	
    questionario_q11 CHAR(1),
    questionario_q12 CHAR(1),
    questionario_q13 CHAR(1),
    questionario_q14 CHAR(1),
    questionario_q15 CHAR(1),
    questionario_q16 CHAR(1),
    questionario_q17 CHAR(1),
    questionario_q18 CHAR(1),
    questionario_q19 CHAR(1),
    questionario_q20 CHAR(1),
    questionario_q21 CHAR(1),
    questionario_q22 CHAR(1),
    questionario_q23 CHAR(1)
)