-- Criação das views silvers referente as tabelas bronze

-- Tabela: Resultados
CREATE OR REPLACE VIEW silver.vw_resultados_2022 AS 
SELECT
    CAST(nu_inscricao AS BIGINT) AS id_inscricao,
    CAST(nu_ano AS INT) AS ano_exame, 
    CAST(no_municipio_esc AS VARCHAR(100)) AS municipio_esc, 
    CAST(sg_uf_esc AS CHAR(2)) AS uf_esc,
    CAST(tp_dependencia_adm_esc AS INT) AS dependencia_adm_esc, 
    CAST(tp_localizacao_esc AS INT) AS localizacao_esc,
    CAST(tp_sit_func_esc AS INT) AS sit_func_escola, 
    CAST(no_municipio_prova AS VARCHAR(100)) AS municipio_prova, 
    CAST(sg_uf_prova AS CHAR(2)) AS uf_prova,  
    CAST(tp_presenca_cn AS INT) AS presenca_cn,
    CAST(tp_presenca_ch AS INT) AS presenca_ch, 
    CAST(tp_presenca_lc AS INT) AS presenca_lc,
    CAST(tp_presenca_mt AS INT) AS presenca_mt, 
    CAST(nu_nota_cn AS NUMERIC(10,2)) AS nota_cn,
    CAST(nu_nota_ch	AS NUMERIC(10,2)) AS nota_ch,
    CAST(nu_nota_lc	AS NUMERIC(10,2)) AS nota_lc,
    CAST(nu_nota_mt	AS NUMERIC(10,2)) AS nota_mt,
    CAST(nu_nota_redacao AS NUMERIC(10,2)) AS nota_redacao,
    CAST(nu_nota_comp1 AS NUMERIC(10,2)) AS nota_comp1,	
    CAST(nu_nota_comp2 AS NUMERIC(10,2)) AS nota_comp2,
    CAST(nu_nota_comp3 AS NUMERIC(10,2)) AS nota_comp3,
    CAST(nu_nota_comp4 AS NUMERIC(10,2)) AS nota_comp4,
    CAST(nu_nota_comp5 AS NUMERIC(10,2)) AS nota_comp5,
    CAST(tp_status_redacao AS INT) AS status_redacao
FROM bronze.raw_resultados_2022;

CREATE OR REPLACE VIEW silver.vw_resultados_2023 AS 
SELECT
    CAST(nu_inscricao AS BIGINT) AS id_inscricao,
    CAST(nu_ano AS INT) AS ano_exame, 
    CAST(no_municipio_esc AS VARCHAR(100)) AS municipio_esc, 
    CAST(sg_uf_esc AS CHAR(2)) AS uf_esc,
    CAST(tp_dependencia_adm_esc AS INT) AS dependencia_adm_esc, 
    CAST(tp_localizacao_esc AS INT) AS localizacao_esc,
    CAST(tp_sit_func_esc AS INT) AS sit_func_escola, 
    CAST(no_municipio_prova AS VARCHAR(100)) AS municipio_prova, 
    CAST(sg_uf_prova AS CHAR(2)) AS uf_prova,  
    CAST(tp_presenca_cn AS INT) AS presenca_cn,
    CAST(tp_presenca_ch AS INT) AS presenca_ch, 
    CAST(tp_presenca_lc AS INT) AS presenca_lc,
    CAST(tp_presenca_mt AS INT) AS presenca_mt, 
    CAST(nu_nota_cn AS NUMERIC(10,2)) AS nota_cn,
    CAST(nu_nota_ch	AS NUMERIC(10,2)) AS nota_ch,
    CAST(nu_nota_lc	AS NUMERIC(10,2)) AS nota_lc,
    CAST(nu_nota_mt	AS NUMERIC(10,2)) AS nota_mt,
    CAST(nu_nota_redacao AS NUMERIC(10,2)) AS nota_redacao,
    CAST(nu_nota_comp1 AS NUMERIC(10,2)) AS nota_comp1,	
    CAST(nu_nota_comp2 AS NUMERIC(10,2)) AS nota_comp2,
    CAST(nu_nota_comp3 AS NUMERIC(10,2)) AS nota_comp3,
    CAST(nu_nota_comp4 AS NUMERIC(10,2)) AS nota_comp4,
    CAST(nu_nota_comp5 AS NUMERIC(10,2)) AS nota_comp5,
    CAST(tp_status_redacao AS INT) AS status_redacao
FROM bronze.raw_resultados_2023;

CREATE OR REPLACE VIEW silver.vw_resultados_2024 AS 
SELECT
    CAST(nu_sequencial AS BIGINT) AS id_sequencial,
    CAST(nu_ano AS INT) AS ano_exame, 
    CAST(no_municipio_esc AS VARCHAR(100)) AS municipio_esc, 
    CAST(sg_uf_esc AS CHAR(2)) AS uf_esc,
    CAST(tp_dependencia_adm_esc AS INT) AS dependencia_adm_esc, 
    CAST(tp_localizacao_esc AS INT) AS localizacao_esc,
    CAST(tp_sit_func_esc AS INT) AS sit_func_escola, 
    CAST(no_municipio_prova AS VARCHAR(100)) AS municipio_prova, 
    CAST(sg_uf_prova AS CHAR(2)) AS uf_prova,  
    CAST(tp_presenca_cn AS INT) AS presenca_cn,
    CAST(tp_presenca_ch AS INT) AS presenca_ch, 
    CAST(tp_presenca_lc AS INT) AS presenca_lc,
    CAST(tp_presenca_mt AS INT) AS presenca_mt, 
    CAST(nu_nota_cn AS NUMERIC(10,2)) AS nota_cn,
    CAST(nu_nota_ch	AS NUMERIC(10,2)) AS nota_ch,
    CAST(nu_nota_lc	AS NUMERIC(10,2)) AS nota_lc,
    CAST(nu_nota_mt	AS NUMERIC(10,2)) AS nota_mt,
    CAST(nu_nota_redacao AS NUMERIC(10,2)) AS nota_redacao,
    CAST(nu_nota_comp1 AS NUMERIC(10,2)) AS nota_comp1,	
    CAST(nu_nota_comp2 AS NUMERIC(10,2)) AS nota_comp2,
    CAST(nu_nota_comp3 AS NUMERIC(10,2)) AS nota_comp3,
    CAST(nu_nota_comp4 AS NUMERIC(10,2)) AS nota_comp4,
    CAST(nu_nota_comp5 AS NUMERIC(10,2)) AS nota_comp5,
    CAST(tp_status_redacao AS INT) AS status_redacao
FROM bronze.raw_resultados_2024;

-- Tabela: Participantes
CREATE OR REPLACE VIEW silver.vw_participantes_2022 AS
SELECT
    CAST(nu_inscricao AS BIGINT) AS id_inscricao,
    CAST(nu_ano AS INT) AS ano_exame,
    CAST(tp_faixa_etaria AS INT) AS faixa_etaria, 
    CAST(tp_sexo AS CHAR(1)) AS sexo,
    CAST(tp_estado_civil AS INT) AS estado_civil, 
    CAST(tp_cor_raca AS INT) AS cor_raca,
    CAST(tp_nacionalidade AS INT) AS nacionalidade,
    CAST(tp_st_conclusao AS INT) AS st_conclusao,	
    CAST(tp_ano_concluiu AS INT) AS ano_conclusao,
    CAST(tp_escola AS INT) AS escola,
    CAST(tp_ensino AS INT) AS ensino,	
    CAST(in_treineiro AS INT) AS treineiro,
    CAST(no_municipio_prova AS VARCHAR(100)) AS municipio_prova,
    CAST(sg_uf_prova AS CHAR(2)) AS uf_prova,	
    CAST(q001 AS CHAR(1)) AS q001,
    CAST(q002 AS CHAR(1)) AS q002,
    CAST(q003 AS CHAR(1)) AS q003,
    CAST(q004 AS CHAR(1)) AS q004,
    CAST(q005 AS INT) AS q005,
    CAST(q006 AS CHAR(1)) AS q006,
    CAST(q007 AS CHAR(1)) AS q007,
    CAST(q008 AS CHAR(1)) AS q008,
    CAST(q009 AS CHAR(1)) AS q009,
    CAST(q010 AS CHAR(1)) AS q010,	
    CAST(q011 AS CHAR(1)) AS q011,
    CAST(q012 AS CHAR(1)) AS q012,
    CAST(q013 AS CHAR(1)) AS q013,
    CAST(q014 AS CHAR(1)) AS q014,
    CAST(q015 AS CHAR(1)) AS q015,
    CAST(q016 AS CHAR(1)) AS q016,
    CAST(q017 AS CHAR(1)) AS q017,
    CAST(q018 AS CHAR(1)) AS q018,
    CAST(q019 AS CHAR(1)) AS q019,
    CAST(q020 AS CHAR(1)) AS q020,
    CAST(q021 AS CHAR(1)) AS q021,
    CAST(q022 AS CHAR(1)) AS q022,
    CAST(q023 AS CHAR(1)) AS q023,
    CAST(q024 AS CHAR(1)) AS q024,
    CAST(q025 AS CHAR(1)) AS q025
FROM bronze.raw_participantes_2022;

CREATE OR REPLACE VIEW silver.vw_participantes_2023 AS
SELECT
    CAST(nu_inscricao AS BIGINT) AS id_inscricao,
    CAST(nu_ano AS INT) AS ano_exame,
    CAST(tp_faixa_etaria AS INT) AS faixa_etaria, 
    CAST(tp_sexo AS CHAR(1)) AS sexo,
    CAST(tp_estado_civil AS INT) AS estado_civil, 
    CAST(tp_cor_raca AS INT) AS cor_raca,
    CAST(tp_nacionalidade AS INT) AS nacionalidade,
    CAST(tp_st_conclusao AS INT) AS st_conclusao,	
    CAST(tp_ano_concluiu AS INT) AS ano_conclusao,
    CAST(tp_escola AS INT) AS escola,
    CAST(tp_ensino AS INT) AS ensino,	
    CAST(in_treineiro AS INT) AS treineiro,
    CAST(no_municipio_prova AS VARCHAR(100)) AS municipio_prova,
    CAST(sg_uf_prova AS CHAR(2)) AS uf_prova,	
    CAST(q001 AS CHAR(1)) AS q001,
    CAST(q002 AS CHAR(1)) AS q002,
    CAST(q003 AS CHAR(1)) AS q003,
    CAST(q004 AS CHAR(1)) AS q004,
    CAST(q005 AS INT) AS q005,
    CAST(q006 AS CHAR(1)) AS q006,
    CAST(q007 AS CHAR(1)) AS q007,
    CAST(q008 AS CHAR(1)) AS q008,
    CAST(q009 AS CHAR(1)) AS q009,
    CAST(q010 AS CHAR(1)) AS q010,	
    CAST(q011 AS CHAR(1)) AS q011,
    CAST(q012 AS CHAR(1)) AS q012,
    CAST(q013 AS CHAR(1)) AS q013,
    CAST(q014 AS CHAR(1)) AS q014,
    CAST(q015 AS CHAR(1)) AS q015,
    CAST(q016 AS CHAR(1)) AS q016,
    CAST(q017 AS CHAR(1)) AS q017,
    CAST(q018 AS CHAR(1)) AS q018,
    CAST(q019 AS CHAR(1)) AS q019,
    CAST(q020 AS CHAR(1)) AS q020,
    CAST(q021 AS CHAR(1)) AS q021,
    CAST(q022 AS CHAR(1)) AS q022,
    CAST(q023 AS CHAR(1)) AS q023,
    CAST(q024 AS CHAR(1)) AS q024,
    CAST(q025 AS CHAR(1)) AS q025
FROM bronze.raw_participantes_2023;

CREATE OR REPLACE VIEW silver.vw_participantes_2024 AS
SELECT
    CAST(nu_inscricao AS BIGINT) AS id_sequencial,
    CAST(nu_ano AS INT) AS ano_exame,
    CAST(tp_faixa_etaria AS INT) AS faixa_etaria, 
    CAST(tp_sexo AS CHAR(1)) AS sexo,
    CAST(tp_estado_civil AS INT) AS estado_civil, 
    CAST(tp_cor_raca AS INT) AS cor_raca,
    CAST(tp_nacionalidade AS INT) AS nacionalidade,
    CAST(tp_st_conclusao AS INT) AS st_conclusao,	
    CAST(tp_ano_concluiu AS INT) AS ano_conclusao,
    CAST(tp_ensino AS INT) AS ensino,	
    CAST(in_treineiro AS INT) AS treineiro,
    CAST(no_municipio_prova AS VARCHAR(100)) AS municipio_prova,
    CAST(sg_uf_prova AS CHAR(2)) AS uf_prova,	
    CAST(q001 AS CHAR(1)) AS q001,
    CAST(q002 AS CHAR(1)) AS q002,
    CAST(q003 AS CHAR(1)) AS q003,
    CAST(q004 AS CHAR(1)) AS q004,
    CAST(q005 AS INT) AS q005,
    CAST(q006 AS CHAR(1)) AS q006,
    CAST(q007 AS CHAR(1)) AS q007,
    CAST(q008 AS CHAR(1)) AS q008,
    CAST(q009 AS CHAR(1)) AS q009,
    CAST(q010 AS CHAR(1)) AS q010,	
    CAST(q011 AS CHAR(1)) AS q011,
    CAST(q012 AS CHAR(1)) AS q012,
    CAST(q013 AS CHAR(1)) AS q013,
    CAST(q014 AS CHAR(1)) AS q014,
    CAST(q015 AS CHAR(1)) AS q015,
    CAST(q016 AS CHAR(1)) AS q016,
    CAST(q017 AS CHAR(1)) AS q017,
    CAST(q018 AS CHAR(1)) AS q018,
    CAST(q019 AS CHAR(1)) AS q019,
    CAST(q020 AS CHAR(1)) AS q020,
    CAST(q021 AS CHAR(1)) AS q021,
    CAST(q022 AS CHAR(1)) AS q022,
    CAST(q023 AS CHAR(1)) AS q023
FROM bronze.raw_participantes_2024;